- name: Add application user
  user: 
    name: "{{APP_USER}}"
    comment: "Student Project Application User"

- name: Install Java
  yum:
    name: java
    state: installed

- name: Download Tomcat
  unarchive: 
    src: "{{TOMCAT_URL}}"
    dest: "{{APP_HOME}}"
    remote_src: yes
  become_user: "{{APP_USER}}"
 
- name: Download a war file
  get_url: 
    url: "{{WAR_URL}}"
    dest: "{{TOMCAT_HOME}}/webapps/student.war"
  become_user: "{{APP_USER}}"

- name: Download a jar file
  get_url: 
    url: "{{JDBC_JAR_URL}}"
    dest: "{{TOMCAT_HOME}}/lib/mysql-connector.jar"
  become_user: "{{APP_USER}}"

- name: Copy TOMCAT configuration
  template: 
    src: "context.xml.j2"
    dest: "{{TOMCAT_HOME}}/conf/context.xml"
  become_user: "{{APP_USER}}"

- name: Download Tomcat systemd script
  get_url:
    url: "{{TOMCAT_SYSTEMD_SCRIPT}}"
    dest: /etc/init.d/tomcat
    mode: 755

- name: Reload systemd
  shell: systemctl daemon-reload

- name: Start Tomcat
  service: 
    name: tomcat
    state: restarted
    enabled: yes