- name: Demo on vars 
  hosts: all 
  vars:
    URL: vars.google.com 
  tasks:
    - name: Access Variable 
      debug:
        msg: "Helloo from {{URL}}" 

- name: Demo in vars in tasks
  hosts: all
  tasks:
    - name: Vars from tasks
      debug: 
        msg: "URL == {{URL}}"
      vars:
        URL: task.google.com

## Note:
## 1. Vars can be given on tasks
## 2. Task vars will override the play vars



- name: Demo on vars from localhost
  hosts: localhost
  vars:
    URL: vars.google.com 
  tasks:
    - name: Access Variable 
      debug:
        msg: "Helloo from {{URL}}" 

- name: Demo on Vars Prompt
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: No
  tasks:
    - name: Access Variable 
      debug:
        msg: "Helloo from {{URL}}"     

- name: Demo on var files 
  hosts: localhost
  vars_files: 
    - var01.yml
  tasks:
    - name: Access Variable 
      debug:
        msg: "URL == {{URL}}"    

- name: Demo on host file variables
  hosts: all
  tasks:
    - name: Access variable
      debug:
        msg: "URL == {{URL}}"