- name: Demo on vars 
  hosts: all 
  vars:
    URL: vars.google.com 
  tasks:
    - name: Access Variable 
      debug:
        msg: "Helloo from {{URL}}" 

- name: Demo on vars from localhost
  hosts: localhost
  vars:
    URL: vars.google.com 
  tasks:
    - name: Access Variable 
      debug:
        msg: "Helloo from {{URL}}" 