- name: Register output of one task in a variable
  hosts: all
  tasks:
    - name: Run shell command
      shell: echo$?
      register: out

    - name: Print uptime
      debug:
        msg: Uptime = "{{out.stdout}}"
         