- name: Demo on privilege escalation
  hosts: all
  become: yes
  tasks: 
    - name: Get id of a user
      shell: id
      register: out
      become: yes

    - name: Print output
      debug:
        msg: "{{out.stdout}}"

  
